site_name: Introducción a la Mecatrónica

theme:
  name: material

# --- AGREGA ESTAS LÍNEAS DESDE AQUÍ ---
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# --------------------------------------

nav:
  - Inicio: index.md
  - Prácticas:
      - Práctica 1: Practicas/Practica1.md
      - Práctica 2: Practicas/Practica2.md
      - Práctica 3: Practicas/Practica3.md
      - Práctica 4: Practicas/Practica4.md
      - Práctica 5: Practicas/Practica5.md
      - Práctica 6: Practicas/Practica6.md